/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * アカウント有効化
         * @description メールで送付されたトークンでアカウントを有効化する
         */
        get: {
            parameters: {
                query: {
                    /** @description アクティベーショントークン */
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * グループ一覧取得
         * @description ログイン中のユーザーが所属するグループ一覧を取得する
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.SwaggerGroup"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * グループ作成
         * @description グループを作成し、メンバーを追加する
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description グループ情報 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["controllers.CreateGroupBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.CreateGroupResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * メッセージ一覧取得
         * @description グループ内のメッセージ一覧を取得する（グループメンバーのみ）
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description グループID */
                    group_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.GetMessagesResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * メッセージ送信
         * @description グループ内にメッセージを送信する（グループメンバーのみ）
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description グループID */
                    group_id: number;
                };
                cookie?: never;
            };
            /** @description メッセージ内容 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["controllers.CreateMessageInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.CreateMessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health_check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ヘルスチェック
         * @description サーバーの稼働状態を確認する
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.HealthCheckResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン
         * @description メールアドレスとパスワードでログインし、セッション Cookie を発行する
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description ログイン情報 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["controllers.LoginInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.LoginResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * プロフィール更新
         * @description ログイン中のユーザーのプロフィールを更新する
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description プロフィール情報 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["controllers.UpdateUserProfileBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.UserProfileResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * プロフィール作成
         * @description ログイン中のユーザーのプロフィールを作成する
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description プロフィール情報 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["controllers.CreateUserProfileBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.UserProfileResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ユーザー登録
         * @description メールアドレスとパスワードで新規ユーザーを登録する
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 登録情報 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["controllers.RegisterInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.RegisterResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tweets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ツイート投稿
         * @description 認証済みユーザーとしてツイートを投稿する
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description ツイート内容 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["controllers.CreateTweetInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.CreateTweetResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tweets-image/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 画像アップロード完了
         * @description S3 へのアップロード完了後、key を確認して画像ツイートを作成する
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description アップロード済み画像の key */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["controllers.CompleteImageTweetInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.CreateImageTweetResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tweets-image/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 画像アップロード許可
         * @description 認証済みユーザー向けに S3 への直接アップロード用 URL と key を発行する
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 画像メタ情報 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["controllers.PresignImageTweetInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.PresignImageTweetResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tweets/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ブックマーク一覧取得
         * @description ログイン中のユーザーのブックマーク一覧を取得する
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.SwaggerBookmark"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tweets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ツイート取得
         * @description 指定IDのツイートを取得する
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ツイートID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.GetTweetResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * ツイート削除
         * @description 認証済みユーザーが自分のツイートを削除する（他人のツイートは削除できない）
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ツイートID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.StatusOKResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tweets/{id}/bookmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ブックマーク追加
         * @description 指定ツイートをブックマークする
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ツイートID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.StatusOKResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * ブックマーク解除
         * @description 指定ツイートのブックマークを解除する
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ツイートID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.StatusOKResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tweets/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * コメント一覧取得
         * @description 指定ツイートのコメントをカーソルページネーションで取得する
         */
        get: {
            parameters: {
                query?: {
                    /** @description ページネーションカーソル（最後に取得したコメントID） */
                    cursor?: number;
                    /** @description 取得件数（1〜100、デフォルト20） */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description ツイートID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.GetCommentsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * コメント作成
         * @description 指定ツイートにコメントする
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ツイートID */
                    id: number;
                };
                cookie?: never;
            };
            /** @description コメント内容 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["controllers.CreateCommentBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.CreateCommentResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tweets/{id}/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * コメント削除
         * @description 指定ツイートの自分のコメントを削除する
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ツイートID */
                    id: number;
                    /** @description コメントID */
                    comment_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.StatusOKResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tweets/{id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * いいね
         * @description 指定ツイートにいいねする
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ツイートID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.StatusOKResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * いいね解除
         * @description 指定ツイートのいいねを解除する
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ツイートID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.StatusOKResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tweets/{id}/retweet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * リツイート
         * @description 指定ツイートをリツイートする
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ツイートID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.StatusOKResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * リツイート解除
         * @description 指定ツイートのリツイートを解除する
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ツイートID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.StatusOKResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 退会
         * @description ログイン中のユーザーアカウントを削除する
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.StatusOKResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/tweets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ログインユーザーのツイート一覧取得
         * @description ログイン中のユーザーのツイートをカーソルページネーションで取得する
         */
        get: {
            parameters: {
                query?: {
                    /** @description ページネーションカーソル（最後に取得したツイートID） */
                    cursor?: number;
                    /** @description 取得件数（1〜100、デフォルト20） */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.GetCurrentUserTweetsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザー情報取得
         * @description 指定IDのユーザー情報を取得する
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ユーザーID */
                    user_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.GetUserResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * フォロー
         * @description 指定ユーザーをフォローする
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description フォロー対象のユーザーID */
                    user_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.StatusOKResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * フォロー解除
         * @description 指定ユーザーのフォローを解除する
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description フォロー解除対象のユーザーID */
                    user_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.StatusOKResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * フォロワー一覧取得
         * @description 指定ユーザーのフォロワーをカーソルページネーションで取得する
         */
        get: {
            parameters: {
                query?: {
                    /** @description ページネーションカーソル */
                    cursor?: number;
                    /** @description 取得件数（1〜100、デフォルト20） */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description ユーザーID */
                    user_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.GetFollowersResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * フォロー中一覧取得
         * @description 指定ユーザーがフォローしているユーザーをカーソルページネーションで取得する
         */
        get: {
            parameters: {
                query?: {
                    /** @description ページネーションカーソル */
                    cursor?: number;
                    /** @description 取得件数（1〜100、デフォルト20） */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description ユーザーID */
                    user_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.GetFollowingResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * プロフィール取得
         * @description 指定ユーザーのプロフィールを取得する
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ユーザーID */
                    user_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.UserProfileResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/retweets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザーのリツイート一覧取得
         * @description 指定ユーザーのリツイートをカーソルページネーションで取得する
         */
        get: {
            parameters: {
                query?: {
                    /** @description ページネーションカーソル（最後に取得したリツイートID） */
                    cursor?: number;
                    /** @description 取得件数（1〜100、デフォルト20） */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description ユーザーID */
                    user_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.GetUserRetweetsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/tweets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザーのツイート一覧取得
         * @description 指定ユーザーのツイートをカーソルページネーションで取得する
         */
        get: {
            parameters: {
                query?: {
                    /** @description ページネーションカーソル（最後に取得したツイートID） */
                    cursor?: number;
                    /** @description 取得件数（1〜100、デフォルト20） */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description ユーザーID */
                    user_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.GetUserTweetsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["controllers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "controllers.CompleteImageTweetInput": {
            /** @example uploads/1_abc123.jpg */
            key: string;
        };
        "controllers.CreateCommentBody": {
            /** @example いいツイートですね！ */
            content: string;
        };
        "controllers.CreateCommentResponse": {
            comment?: components["schemas"]["controllers.SwaggerComment"];
        };
        "controllers.CreateGroupBody": {
            /**
             * @example [
             *       2,
             *       3
             *     ]
             */
            member_user_ids?: number[];
            /** @example グループ名 */
            name: string;
        };
        "controllers.CreateGroupResponse": {
            group?: components["schemas"]["controllers.SwaggerGroup"];
        };
        "controllers.CreateImageTweetItem": {
            /** @example https://example.com/image.jpg */
            image_url?: string;
            /** @example 1 */
            user_id?: number;
        };
        "controllers.CreateImageTweetResponse": {
            tweet?: components["schemas"]["controllers.CreateImageTweetItem"];
        };
        "controllers.CreateMessageInput": {
            /** @example メッセージ本文 */
            content: string;
        };
        "controllers.CreateMessageItem": {
            /** @example メッセージ本文 */
            content?: string;
            /** @example 1 */
            group_id?: number;
            /** @example 1 */
            user_id?: number;
        };
        "controllers.CreateMessageResponse": {
            message?: components["schemas"]["controllers.CreateMessageItem"];
        };
        "controllers.CreateTweetInput": {
            /** @example Hello, world! */
            content: string;
        };
        "controllers.CreateTweetItem": {
            /** @example Hello, world! */
            content?: string;
            /** @example 1 */
            user_id?: number;
        };
        "controllers.CreateTweetResponse": {
            tweet?: components["schemas"]["controllers.CreateTweetItem"];
        };
        "controllers.CreateUserProfileBody": {
            /** @example 自己紹介文です */
            bio?: string;
            /** @example https://example.com/avatar.png */
            image_url?: string;
            /** @example Tokyo */
            location?: string;
            /** @example たろう */
            name?: string;
        };
        "controllers.ErrorResponse": {
            /** @example エラーメッセージ */
            error?: string;
        };
        "controllers.GetCommentsResponse": {
            comments?: components["schemas"]["controllers.SwaggerComment"][];
            /** @example false */
            has_more?: boolean;
            next_cursor?: number;
        };
        "controllers.GetCurrentUserTweetsResponse": {
            /** @example false */
            has_more?: boolean;
            next_cursor?: number;
            tweets?: components["schemas"]["controllers.SwaggerTweet"][];
            user?: components["schemas"]["controllers.SwaggerUserDetail"];
        };
        "controllers.GetFollowersResponse": {
            followers?: components["schemas"]["controllers.SwaggerFollow"][];
            /** @example false */
            has_more?: boolean;
            next_cursor?: number;
        };
        "controllers.GetFollowingResponse": {
            following?: components["schemas"]["controllers.SwaggerFollow"][];
            /** @example false */
            has_more?: boolean;
            next_cursor?: number;
        };
        "controllers.GetMessagesResponse": {
            messages?: components["schemas"]["controllers.SwaggerMessage"][];
        };
        "controllers.GetTweetResponse": {
            tweet?: components["schemas"]["controllers.SwaggerTweet"];
        };
        "controllers.GetUserResponse": {
            user?: components["schemas"]["controllers.SwaggerUserDetail"];
        };
        "controllers.GetUserRetweetsResponse": {
            /** @example false */
            has_more?: boolean;
            next_cursor?: number;
            retweets?: components["schemas"]["controllers.SwaggerRetweetItem"][];
        };
        "controllers.GetUserTweetsResponse": {
            /** @example false */
            has_more?: boolean;
            next_cursor?: number;
            tweets?: components["schemas"]["controllers.SwaggerTweet"][];
        };
        "controllers.HealthCheckResponse": {
            /** @example ok */
            status?: string;
        };
        "controllers.LoginInput": {
            /** @example user@example.com */
            email: string;
            /** @example Password1! */
            password: string;
        };
        "controllers.LoginResponse": {
            /** @example ログインに成功しました */
            message?: string;
            user?: components["schemas"]["controllers.LoginUser"];
        };
        "controllers.LoginUser": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example user@example.com */
            email?: string;
            /** @example 1 */
            id?: number;
            /** @example true */
            is_active?: boolean;
        };
        "controllers.MessageResponse": {
            /** @example 処理が完了しました */
            message?: string;
        };
        "controllers.PresignImageTweetInput": {
            /** @example image/jpeg */
            content_type: string;
            /** @example 102400 */
            size: number;
        };
        "controllers.PresignImageTweetResponse": {
            /** @example uploads/1_abc123.jpg */
            key?: string;
            /** @example https://example.com/bucket/uploads/1_abc123.jpg */
            public_url?: string;
            /** @example https://s3.example.com/bucket/uploads/1_abc123.jpg?X-Amz-Signature=... */
            upload_url?: string;
        };
        "controllers.RegisterInput": {
            /** @example user@example.com */
            email: string;
            /** @example Password1! */
            password: string;
        };
        "controllers.RegisterResponse": {
            /** @example ユーザー登録が完了しました */
            message?: string;
            user?: components["schemas"]["controllers.RegisterUserResponse"];
        };
        "controllers.RegisterUserResponse": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example user@example.com */
            email?: string;
            /** @example 1 */
            id?: number;
        };
        "controllers.StatusOKResponse": {
            /** @example ok */
            status?: string;
        };
        "controllers.SwaggerBookmark": {
            /** @example ツイート本文 */
            content?: string;
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example 1 */
            id?: number;
            /** @example 1 */
            tweet_id?: number;
            /** @example 1 */
            user_id?: number;
        };
        "controllers.SwaggerComment": {
            /** @example いいツイートですね！ */
            content?: string;
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example 1 */
            id?: number;
            /** @example 1 */
            tweet_id?: number;
            /** @example 1 */
            user_id?: number;
        };
        "controllers.SwaggerFollow": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example 2 */
            followed_user_id?: number;
            /** @example 1 */
            id?: number;
            /** @example 1 */
            user_id?: number;
        };
        "controllers.SwaggerGroup": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example 1 */
            id?: number;
            /** @example グループ名 */
            name?: string;
            /** @example 1 */
            user_id?: number;
        };
        "controllers.SwaggerMessage": {
            /** @example メッセージ本文 */
            content?: string;
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example 1 */
            group_id?: number;
            /** @example 1 */
            id?: number;
            /** @example 1 */
            user_id?: number;
        };
        "controllers.SwaggerRetweetItem": {
            tweet?: components["schemas"]["controllers.SwaggerTweet"];
        };
        "controllers.SwaggerTweet": {
            /** @example 0 */
            comment_count?: number;
            /** @example Hello, world! */
            content?: string;
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example 1 */
            id?: number;
            /** @example 0 */
            like_count?: number;
            /** @example 0 */
            retweet_count?: number;
            /** @example 2024-01-01T00:00:00Z */
            updated_at?: string;
            /** @example 1 */
            user_id?: number;
        };
        "controllers.SwaggerUserDetail": {
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example user@example.com */
            email?: string;
            /** @example 1 */
            id?: number;
            /** @example true */
            is_active?: boolean;
            /** @example 2024-01-01T00:00:00Z */
            updated_at?: string;
        };
        "controllers.SwaggerUserProfile": {
            /** @example 自己紹介文のサンプル文です */
            bio?: string;
            /** @example 2024-01-01T00:00:00Z */
            created_at?: string;
            /** @example 1 */
            id?: number;
            /** @example https://example.com/avatar.png */
            image_url?: string;
            /** @example 東京 */
            location?: string;
            /** @example Taro007 */
            name?: string;
            /** @example 2024-01-01T00:00:00Z */
            updated_at?: string;
            /** @example 1 */
            user_id?: number;
        };
        "controllers.UpdateUserProfileBody": {
            /** @example 自己紹介文です */
            bio?: string;
            /** @example https://example.com/avatar.png */
            image_url?: string;
            /** @example Tokyo */
            location?: string;
            /** @example たろう */
            name?: string;
        };
        "controllers.UserProfileResponse": {
            profile?: components["schemas"]["controllers.SwaggerUserProfile"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
